### ISSUE TITLE
Write an explanation of major cascades

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami#25]

**Comment by notlee** [comment]
## The Major Cascade

What's a major cascade; who wants them; who needs them; why are they a thing?

### What Is A Major Cascade?

#### A Major Component Release Which Impacts Many Other Dependent Projects

_(This section includes content from the [major cascade blog post](https://origami.ft.com/blog/2019/10/31/major-cascade/), plus a note on why we have to upgrade step by step)_

The Origami team maintain around 52 front end components. A component is a shared piece of user-interface which, along with other components, is used to build a webpage.

Some components are low level — fundamental building blocks used to build many other components and end products. o-typography is an example of a low level component.

Other components are high level — complex components which are used in end products and rarely used to build other components. o-table is an example of a high level component.

As low level components are used to build other components there are more projects between them and the end product. To make major changes to a low level component means upgrading each project in-between step by step.

The below is an example graph of product dependencies. Low level components o-colors and o-typography branch out; they are included in final products directly and indirectly via other components including o-table. In reality the graph is much more complex because many projects comprise "ft.com".

![Screenshot 2020-03-02 at 16 23 16](https://user-images.githubusercontent.com/10405691/75695552-2ac17400-5ca2-11ea-9ee0-f57f9ab0131c.png)

Dependencies on o-typography, a low level dependency, are a large portion of the overall graph. Components in-between including o-buttons and o-table must be upgraded before the end products can be upgraded.

![Screenshot 2020-03-02 at 16 23 19](https://user-images.githubusercontent.com/10405691/75695567-30b75500-5ca2-11ea-8fbe-860000cba91f.png)

Dependencies on o-table, a high level dependency, are a small portion of the overall graph. If a major version of o-table is released the end products may be updated immediately.

![Screenshot 2020-03-02 at 16 23 25](https://user-images.githubusercontent.com/10405691/75695579-357c0900-5ca2-11ea-88a2-1a75b3fddf66.png)

The reason we have to upgrade step by step is that two versions of the same component cannot be used at the same time. In other words we enforce a flat dependency tree, because:
- design consistency (e.g. if o-colors removes a colour usecase, we should stop using it not include two versions of o-colors)
- performance (e.g. only one version of a component should be downloaded / parsed by a client)
- we don't support otherwise (e.g. it's likely to cause errors if two versions of a component are initialised on a page)

#### The Process Of Rolling Out A Major Cascade To End Products

When we talk about "The Major Cascade" we are referring to the process of organising and rolling out the changes to the projects and end products maintained by Origami users.

For the last major cascade we communicated upcoming changes via Slack announcements, email newsletters, a blog post, and meetings with principle engineers and delivery teams in the months prior to releasing upgraded Origami components.

For some of our users communication of the upcoming changes with an open offer of support seemed sufficient for them to upgrade their projects at a time appropriate for their team. For the Customer Products group, who maintain a large number of interconnected projects of varying ages, an upgrade of low level components was more challenging.

To upgrade Customer Products projects first they had to figure out what projects were involved and the order of migration which can be [seen in this Google Sheet](https://docs.google.com/spreadsheets/d/1cmxGQp5ZgtAwSkS8Rww_4vk8xvN-GB9iAhNQf9iwcYs/edit#gid=1320807547) (made using a modified version of [origami-migration-guru](https://github.com/financial-times/origami-migration-guru)). With the support of the delivery team a group of engineers (around 10-12) then worked on the migration over two weeks, with a long tail and few engineers to finish as we ran out of time and the end of December approached. The Origami team also supported directly with migration work. It's this part particularly that makes updating low level components challenging. Why did we approach the Customer Products major cascade this way?

###### Order Matters

We have discussed that to make major changes to a low level component means upgrading each project in-between step by step, in an ordered fashion, to maintain a flat dependency tree.

As a real world example, to upgrade a major version of `o-colors` in `next-article` you first have to upgrade `o-colors` in its dependencies. You have to upgrade `n-ui`, but to upgrade `n-ui` you have to upgrade `n-handlebars` first, to upgrade `n-handlebars` you have to upgrade `n-topic-card` first, to upgrade `n-topic-card` you have to upgrade `n-myft-ui` first, etc, etc...

We refereed to [this Google Sheet](https://docs.google.com/spreadsheets/d/1cmxGQp5ZgtAwSkS8Rww_4vk8xvN-GB9iAhNQf9iwcYs/edit#gid=1320807547) for the Customer Products side of the major cascade.

###### Speed Matters

Most project dependencies like `n-myft-ui` are also included by multiple separate products. `n-myft-ui` is used by `next-search-page` as well as `next-article` for instance. If the Tailored Experiences team upgraded their projects to the latest version of `o-colors` quickly, including `n-myft-ui`, they would not be able to roll out new features to `next-search-page` until it and all of its dependencies are upgraded. This would block the Tailored Experiences team from rolling out new features and bugfixes, unless they duplicated their effort and backported changes to previous major version of their projects. Completing the major cascade within a short time frame mitigates the time other teams are blocked, or have to maintain multiple versions of projects.

###### Ownership Matters

Related to [Speed Matters](#speed-matters), if teams upgrade there projects at different rates then they may become blocked. Some projects in the migration chain may not have an owner at all. A dedicated migration team can coordinate and take ownership of such projects for the purposes of completing the major cascade quickly.

###### Knowledge Sharing And Feedback Loops Matter

A group of people bought together from different teams can share solutions to issues raised by the migration and feedback to the Origami team in real time.

### Removing Or Improving The Major Cascade

The major cascade can be painful. It involves a lot of coordination and dedicated engineering effort. Particularly the Customer Products rollout. Are we able to improve this process to rollout major low level component changes more smoothly?

**Comment by notlee** [comment]
I would live feedback [on this](https://github.com/Financial-Times/origami-proposals/issues/25#issuecomment-593492253). Is it accurate and what have a missed?

@Financial-Times/origami-core do you see us making suggestions in this issue on how to avoid or improve the major cascade?

**Comment by chee** [comment]
this looks great :) it's good to have it written down so we can revisit it as we find new solutions for these parts:

>
> - design consistency (e.g. if o-colors removes a colour usecase, we should stop using it not include two versions of o-colors)
> - performance (e.g. only one version of a component should be downloaded / parsed by a client)
> - we don't support otherwise (e.g. it's likely to cause errors if two versions of a component are initialised on a page)
>

like, users using `lockspot` get failing builds if there are multiple versions of the same component on the page. and `oat`'s verification might help them debug the problem.

the ownership problem is a something we (@financial-times/origami-core) can't fix, though. :(

**Comment by JakeChampion** [comment]
This is a great addition :-) Where should this text live?

**Comment by notlee** [comment]
Let's put it on origami.ft.com on its own page, and link to it from the [Component Versioning docs](https://origami.ft.com/docs/components/versioning/) and [Component Release Notice spec](https://origami.ft.com/spec/v1/components/#component-release-notice). I'll tweak the copy a little so its more "wow now, wanna release a major of a low level component, maybe think about this and see if it's still relevant".

???

**Comment by JakeChampion** [comment]
@notlee good idea :-)
