### ISSUE TITLE
fix percy not having baselines

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami#299]
For some reason percy is never saving baselines? 

it thinks every component is new every time

**Comment by JakeChampion** [comment]
I think this may have been a temporary issue which happened when we updated all the percy projects to have the linked github repo become this repo instead of the old component-specific repos.

I made a [draft PR](https://github.com/Financial-Times/origami/pull/300) to get percy to run on lots of components and they all look to have the correct baseline images recorded

**Comment by chee** [comment]
I think you're right, @JakeChampion. This does appear to be working fine now. We can re-open if it re-emerges
