### ISSUE TITLE
Add "main" field to package.json

### ISSUE THREAD

**Issue by aendra-rininsland** [Financial-Times/origami#485]
`package.json` files in Origami tend to specify a `browser` field but not a `main` field. This makes it substantively more difficult to use with build tools, particularly more opinionated ones like NextJS.

Is there any reason why Origami doesn't provide a `main` field in `package.json`, particularly when it already provides a `browser` field referencing the transpiled output? In my experience, pretty much all front-endian npm packages I've ever consumed have pointed the `main` field at the transpiled output.

**Comment by notlee** [comment]
Hey 👋 

## Browser Field

[The `package.json` docs say](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#browser) the following about the browser field, I guess providing a `main` field too would defeat the point. But @JakeChampion or @chee might have more context about the decision to use the `browser` field over `main`:
>If your module is meant to be used client-side the browser field should be used instead of the main field. This is helpful to hint users that it might rely on primitives that aren't available in Node.js modules. (e.g. window)

Origami component JS does only support a browser environment, the first thing it does is `document.addEventListener` which would error in an SSR context. So I guess it makes sense to be explicit by using the `browser` field.

## NextJS

It looks like `NextJS` initialises 2 instances of webpack? One that resolves the `browser` field and one that doesn't. I think that because... 

The following config in `next.config.js`:
```
module.exports = {
  reactStrictMode: true,
  webpack: (config, options) => {
    console.log(config.resolve.mainFields);
    return config;
  }
}
```
Outputs:
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
[ 'browser', 'module', 'main' ]
[ 'main', 'module' ]
```

I found by adding `browser` to the `mainFields` of both webpack instances (?) I could get `oHeader` setup in a NextJS app:
```
module.exports = {
  reactStrictMode: true,
  webpack: (config, options) => {
    console.log(config.resolve.mainFields);
    config.resolve.mainFields.push('browser');
    return config;
  }
}
```

That doesn't feel right though. 🤔 

For reference here's the JS for my test NextJS page

```
import React from 'react'

class Header extends React.Component {
	constructor(props) {
		super(props);
	}

	async componentDidMount() {
		const oHeader = (await import('@financial-times/o-header')).default;
		this.headerInstance = new oHeader(this.el);
		console.log(this.headerInstance);
	}

	componentWillUnmount() {
		this.headerInstance.destroy();
	}

	render() {
		return <div o-data-component="pretent-I-am-o-header-markup" ref={el => this.el = el} />;
	}
}

export default function Home() {
	return (
		<Header />
		)
	}
```

**Comment by notlee** [comment]
Oh, the [NextJS docs](https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config) say:

```
The webpack function is executed twice, once for the server and once for the client. This allows you to distinguish between client and server configuration using the isServer property.
```

So I guess `componentDidMount` is being executed for SSR and can't resolve o-header. Makes sense! Maybe it should be in `useEffect`? https://nextjs.org/docs/migrating/from-create-react-app#safely-accessing-web-apis

**Comment by aendrew** [comment]
> Origami component JS does only support a browser environment, the first thing it does is document.addEventListener which would error in an SSR context. So I guess it makes sense to be explicit by using the browser field.

This is interesting, thanks for the explanation. I think this means we're using Origami incorrectly in [g-components](https://github.com/financial-times/g-components/), effectively this means that *all* Origami JS should be instantiated in `useEffect` hooks because of the `document.addEventListener` side-effect implicit in every Origami component.

Perhaps one way of making this behaviour more intuitive to use in the future would be to drop that behaviour and assume consuming users will instantiate the Origami JS themselves. Alternately, have two entrypoints for every module — `main.js` and `browser.js`, the latter simply being a version of the former that uses the `document.addEventListener` idiom. This would improve utility within SSR contexts without breaking backwards compatibility at all.

Closing as it seems this is pretty well-explained at this point. Thanks again @notlee!! 🙌

**Comment by notlee** [comment]
I think both of those ideas make sense. I'm going to reopen the issue to remember to chat about it with the team :)

**Comment by aendrew** [comment]
@notlee Cool 👍  FWIW, I tried that workaround and it still doesn't work if you statically import Origami (as we do in `g-components`), because of the side-effect you mention (see https://github.com/Financial-Times/g-components/issues/211). My feeling is that what I propose in that issue will break `g-components` because that will inherently create a tooling dependency on Webpack's dynamic imports. 

AFAICT the only way to really resolve this in a component library idiom is to ensure that module imports don't have side-effects.

**Comment by chee** [comment]
> Perhaps one way of making this behaviour more intuitive to use in the future would be to drop that behaviour and assume consuming users will instantiate the Origami JS themselves. Alternately, have two entrypoints for every module — `main.js` and `browser.js` (with each file pointing to their respective fields in `package.json`), the latter simply being a version of the former that uses the `document.addEventListener` idiom. This would improve utility within SSR/component library contexts without breaking backwards compatibility at all.

there's more to it than just this `document.addEventListener` in the main import.

A lot of our components touch `window` and `document`, only available in a browser context. eventually perhaps we can get to a place where the javascript for our components is able to run on the server, but that is a long ways off. instantiating the Origami JS in `useEffect` is how we do it in our storybook stories.

```js
useEffect(() => void footer.init(), [])
```

**Comment by aendrew** [comment]
@chee But it's fine if components touch `window` and `document`, so long as they're wrapped in a function call. The problem I constantly run into with the current idiom is that they touch `window` and `document` on module import, so I *can't* instantiate whatever component in useEffect as that would mean having to dynamically import the Origami component inside `useEffect()`. I'm experimenting with that approach at the moment, but it seems a bit perilous? Possibly I'm overthinking it.

**Comment by JakeChampion** [comment]
Even if we removed the code which runs on importing which relies on `window` and `document`, the code will still not actually work on nodejs.

I do believe we are currently doing the correct thing  by not using the `main` property as that is intended for nodejs projects and we do not support running components on nodejs.

If and/or when the browser tooling community settles on a name within ["conditional package exports"](https://nodejs.org/dist/latest-v16.x/docs/api/packages.html#conditional-exports) which can be used to point to browser js files, we will move to that and we can then expose multiple different entry points. E.G. Keep our existing export which relies on `window` and `document` and have another export which does not run any code during import.

**Comment by notlee** [comment]
Closing this in favour of global checks in the browser entry point: https://github.com/Financial-Times/origami/pull/712#issuecomment-1104025451
