### ISSUE TITLE
Fix code example width and top margin

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami#73]
E.g. This should have less margin between the copy and the example, and should span the full width of main.

<img width="817" alt="screenshot 2019-03-01 at 11 39 01" src="https://user-images.githubusercontent.com/10405691/53635995-ad8a9b80-3c16-11e9-813c-5d3255e7bf18.png">

Is this an o-layout thing?

**Comment by chee** [comment]
it's only noticeable on the ones with background colours, but everything that's been `float: left` no longer gets its default `width` from its container for some reason that i'm not clear on from reading [the float spec]. i gather it's because a floated item's width becomes the width of its own content (rather than the width of the container), so things can float around it.

think we can fix it by adding a `width: 100%` to the grid-L `.o-layout.o-layout--docs > .o-layout__main > *`, which already has a `max-width` of `max-width: calc(100% - 16.5rem - 1rem);`. in `o-layout` here: https://github.com/Financial-Times/o-layout/blob/e94e073148e57d4f95d30ac5afa13ee9bc5e0c23/src/scss/_grid.scss#L98-L103
